version: "3.1"
services:
  elasticsearch:
    container_name: elastic_search
    image: elasticsearch:7.17.6
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_tutorial:/usr/share/elasticsearch/data
    networks:
      - es_tutorial_net
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
  logstash:
    container_name: es-tutorial-logstash
    image: logstash:7.17.5
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      # bind mount in the container must be the same with file input in
      # './logstash/pipeline/logstash.conf'
      - ./logstash/data:/usr/share/data
    networks:
      - es_tutorial_net
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:7.17.6
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic_search:9200
    networks:
      - es_tutorial_net
    depends_on:
      - elasticsearch

volumes:
  elasticsearch_tutorial:
networks:
  es_tutorial_net:
